[package]
name = "porus"
description = "porus library"
version = "0.0.0"
authors = ["bhuztez <bhuztez@gmail.com>"]
license = "MIT"
edition = '2021'

[dependencies]
porus_macros = { path = "porus_macros" }

[dev-dependencies]
proptest = "1.1.0"

[features]
local-judge = []
online-judge = []

[profile.release]
panic = "abort"
opt-level = 2
incremental = false
codegen-units = 1
